# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_version = ">= 1.5.4"
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "aws_region" {
  type    = string
  default = "us-west-1"
}

variable "module_version" {
  type    = string
  default = "0.11.0"
}

variable "consul_version" {
  type    = string
  default = "1.9.2"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "amazon-ebs" "ubuntu" {
  ami_description             = "An Ubuntu AMI that has Consul, Patroni and TimescaleDB installed."
  ami_name                    = "tsdb-ubuntu-${uuidv4()}"
  instance_type               = "t2.micro"
  region                      = "${var.aws_region}"
  associate_public_ip_address = true
  source_ami_filter {
    filters = {
      name                = "ubuntu/images/*ubuntu-focal-20.04-amd64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"] # Canonical
  }
  ssh_username = "ubuntu"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.amazon-ebs.ubuntu"]

  provisioner "shell" {
    inline = [
      "sleep 60",
      "cd /tmp",
      "wget https://github.com/hashicorp/terraform-aws-consul/archive/refs/tags/v${var.module_version}.tar.gz -O module.tar.gz",
      "tar -xvf module.tar.gz"
    ]
  }

  provisioner "shell" {
    inline = ["/tmp/terraform-aws-consul-${var.module_version}/modules/install-consul/install-consul --version ${var.consul_version}"]
  }

  provisioner "shell" {
    inline       = ["/tmp/terraform-aws-consul-${var.module_version}/modules/setup-systemd-resolved/setup-systemd-resolved"]
    pause_before = "30s"
  }

  provisioner "shell" {
    inline = [
      "sudo apt-get update",
      "sudo apt-get install -y postgresql-common",
      "sudo sh /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y",
      "sudo sh -c \"echo 'deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main' > /etc/apt/sources.list.d/timescaledb.list\"",
      "wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/timescale.keyring",
      "sudo apt-get update",
      "sudo apt-get install -y timescaledb-2-postgresql-13",
      "sudo systemctl stop postgresql",
      "sudo systemctl disable postgresql"
    ]
  }

  provisioner "shell" {
    inline = [
      "sudo apt-get install -y python3-psycopg2 python3-pip",
      "sudo pip install patroni[consul]"
    ]
  }

}
