"""Add house.cert_arn

Revision ID: 05476c7997eb
Revises: b8464db3feb8
Create Date: 2021-10-15 18:10:44.531194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05476c7997eb'
down_revision = 'b8464db3feb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('cert_arn', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'cert_arn')
    # ### end Alembic commands ###
