"""Add House model.

Revision ID: 08e383bb915f
Revises: d45ddbe7f0b9
Create Date: 2021-10-15 13:53:21.130814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e383bb915f'
down_revision = 'd45ddbe7f0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('house_id')
    )
    op.add_column('device', sa.Column('house_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'house', ['house_id'], ['house_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'house_id')
    op.drop_table('house')
    # ### end Alembic commands ###
