"""Update Analytics.

Revision ID: 4d17a2ffbc74
Revises: 65099af7d24f
Create Date: 2021-10-28 19:07:25.276207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d17a2ffbc74'
down_revision = '65099af7d24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('continuous_aggregation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'continuous_aggregation')
    # ### end Alembic commands ###
