"""Make device.house_id not nullable.

Revision ID: b8464db3feb8
Revises: ce1e631883a8
Create Date: 2021-10-15 14:06:07.972446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8464db3feb8'
down_revision = 'ce1e631883a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'house_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'house_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
