"""Add house_id to device index.

Revision ID: ce1e631883a8
Revises: 08e383bb915f
Create Date: 2021-10-15 14:00:11.914671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1e631883a8'
down_revision = '08e383bb915f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_device_house_id'), 'device', ['house_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_house_id'), table_name='device')
    # ### end Alembic commands ###
